[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache = true
cache_path = "cache"
broadcast = "broadcast"

# Import remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@forge-std/=lib/forge-std/src/"
]

solc_version = "0.8.31"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = true