[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache = true
cache_path = "cache"
broadcast = "broadcast"

remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
]

solc_version = "0.8.34"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = true